## Finds the cheapest machine for every campaign level.
##
## Run from the project folder:
##   godot_console --headless --path . --script res://tools/level_solver.gd
## Writes docs/level-report.md and exits with code 1 if a level is broken:
## its reference solution fails, it can't be solved by any machine, a
## machine cheaper than its three-star count exists, a wrong machine within
## its two-star budget gets past the drops its cards show (check_decode), or
## its waits_for doesn't match the inventions it can't be built without
## (check_waits).
##
## Why a search is enough: with one-drop tubes every piece takes one drop per
## input and gives one per output, and loops can never start (a loop waits on
## itself). So every working machine weaves stitch i from the i-th color of
## each card: it is a function of the cards. The search tries every function
## that the level's pieces can build, cheapest first, and compares it with
## the target on the card colors the level actually uses. Splits are free, so
## any result can feed any number of pieces.
extends SceneTree

const Paint = preload("res://core/paint.gd")
const Level = preload("res://core/level.gd")
const Simulator = preload("res://core/simulator.gd")
const Invention = preload("res://core/invention.gd")
const Functions = preload("res://tools/functions.gd")

const LANES := 20  # colors packed per int (3 flags each)
## The two-input operations the search knows, by piece or invention check.
const BINARY := ["mix", "filter", "contrast", "third_paint", "missing_from_either", "same_paint"]

var problems := 0
var chunks := 0
var full_mask := PackedInt64Array()
var low_mask := PackedInt64Array()
var high_mask := PackedInt64Array()
var red_vec := PackedInt64Array()
var combo_count := 0
var has_split := false
var target_key := ""
var ops: Array = []
var visited := {}
var found := ""
var nodes_seen := 0
var card_signals: Array = []  # the cards, as the last solve() packed them


func _init() -> void:
	var t0 := Time.get_ticks_msec()
	var levels := Level.load_all()
	var by_level := Invention.reference_inventions_by_level(levels)
	var lines := PackedStringArray()
	lines.append("# Chromaton level report")
	lines.append("")
	lines.append("Generated by `tools/level_solver.gd` on %s. Rerun after changing levels or pieces:" % Time.get_date_string_from_system())
	lines.append("")
	lines.append("```")
	lines.append("godot_console --headless --path . --script res://tools/level_solver.gd")
	lines.append("```")
	lines.append("")
	lines.append("**Cheapest** is the fewest pieces any machine needs to weave the level (splits free where the level offers them, otherwise each result feeds one piece; an invention at its reference price, which is its machine minus one, never below 1). It is found by trying every machine the level's pieces can build, cheapest first. Three stars need the cheapest count; two stars need the budget.")
	lines.append("")
	lines.append("**Shows** is how many drops a card shows at the start: every wrong machine within the ★★ budget fails within them, so they are all the player needs to work out the rule. **Waits for** names the inventions a level can't be built without (proven: no machine of the rest of its tray weaves it); the level stays locked until the player owns them.")
	lines.append("")
	lines.append("| Level | Stitches | Cards | Card combos | Shows | Reference | Ticks | Cheapest | Cheapest machine | ★★ budget | ★★★ best | Waits for |")
	lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
	for level in levels:
		if level.error != "":
			_fail(level.error)
			continue
		var inventions: Dictionary = by_level[level.number - 1]
		var m = level.reference_machine()
		var sim = Simulator.new(m, level.cards, level.target, inventions)
		sim.run()
		var ref_cost: int = m.cost(inventions)
		if sim.status != Simulator.Status.SOLVED:
			_fail("%s: reference solution does not solve the level (status %d, stitch %d)" % [level.id, sim.status, sim.wrong_index])
		if ref_cost != level.best:
			_fail("%s: reference uses %d pieces but best is %d" % [level.id, ref_cost, level.best])
		if level.budget < level.best:
			_fail("%s: budget %d is under best %d" % [level.id, level.budget, level.best])
		var res := solve(level, inventions, level.best)
		var cheapest: String = str(res["cost"]) if res["cost"] >= 0 else "> %d" % level.best
		if res["cost"] >= 0 and res["cost"] < level.best:
			_fail("%s: a %d-piece machine exists (%s), cheaper than best %d" % [level.id, res["cost"], res["program"], level.best])
		if res["cost"] < 0:
			_fail("%s: no machine of up to %d pieces found" % [level.id, level.best])
		var waits := check_waits(level, inventions)
		check_decode(level, inventions)
		lines.append("| %d. %s | %d | %d | %d | %s | %d | %d | %s | `%s` | %d | %d | %s |" % [
			level.number, level.name, level.size(), level.cards.size(), res["combos"],
			str(level.card_shows) if not level.cards.is_empty() else "–", ref_cost, sim.tick,
			cheapest, res["program"], level.budget, level.best, ", ".join(waits) if not waits.is_empty() else "–"])
		print("%s: cheapest %s  %s  (%d states)" % [level.id, cheapest, res["program"], res["states"]])
	lines.append("")
	lines.append("---")
	lines.append("")
	lines.append("Checks: %s. Run time %.1f s." % ["all passed" if problems == 0 else "%d problem(s)" % problems, (Time.get_ticks_msec() - t0) / 1000.0])
	var f := FileAccess.open("res://docs/level-report.md", FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	quit(1 if problems > 0 else 0)


func _fail(msg: String) -> void:
	problems += 1
	printerr("PROBLEM: " + msg)


## A level waits for exactly the inventions it can't be built without: for
## each invention it offers, either a machine without it weaves the cloth
## (searched up to a few pieces past the budget), or every machine the rest
## of the tray can build is listed and none weaves it. Returns the
## inventions proven needed.
func check_waits(level, inventions: Dictionary) -> Array:
	var needed := []
	for inv_id in level.inventions:
		var res := solve(level, inventions, level.budget + 4, inv_id)
		if res["cost"] >= 0:
			if inv_id in level.waits_for:
				_fail("%s waits for %s but %s weaves it without" % [level.id, inv_id, res["program"]])
			continue
		var closed := _closure(CLOSURE_CAP)
		if closed < 0:
			_fail("%s: can't tell whether it needs %s (more than %d machines without it)" % [level.id, inv_id, CLOSURE_CAP])
		elif closed == 0:
			_fail("%s: no machine without %s exists up to %d pieces, but some might beyond" % [level.id, inv_id, level.budget + 4])
		else:
			needed.append(inv_id)
			if not inv_id in level.waits_for:
				_fail("%s can't be built without %s but doesn't wait for it (waits_for)" % [level.id, inv_id])
	for inv_id in level.waits_for:
		if not inv_id in level.inventions:
			_fail("%s waits for %s, which it doesn't offer" % [level.id, inv_id])
	return needed


const CLOSURE_CAP := 20000

## Every paint table the last solve()'s pieces can make from the cards, at
## any cost: 1 if the list closes without the target (no machine can weave
## it), 0 if the target is among them, -1 if the list passes `cap`.
func _closure(cap: int) -> int:
	var have := {}
	var list := []
	for s in card_signals:
		if not have.has(s["key"]):
			have[s["key"]] = true
			list.append(s)
	var k := 0
	while true:
		for g in _gates(list, 1 << 30):
			if not have.has(g["key"]):
				have[g["key"]] = true
				list.append(g)
		if have.has(target_key):
			return 0
		if list.size() > cap:
			return -1
		if list.size() == k:
			return 1
		k = list.size()
	return -1


## What a card shows decodes the level: every wrong machine within the
## two-star budget fails within the drops a card shows (card_shows). Returns
## the fewest drops that would do (at least CARD_SHOWS_MIN), or -1 if some
## wrong machine gets past every drop shown.
func check_decode(level, inventions: Dictionary) -> int:
	if level.cards.is_empty():
		return 0
	var fn = Functions.new()
	var funcs: Array = fn.cheap_functions(level_ops(level, inventions), level.cards.size(), level.budget)
	var combos := Functions.stitch_combos(level.cards, level.size())
	var needed := Level.CARD_SHOWS_MIN
	var late := 0
	for f in funcs:
		var w := Functions.first_wrong(f, combos, level.target)
		if w >= level.card_shows:
			late += 1
		needed = maxi(needed, w + 1)
	if late > 0:
		_fail("%s: %d wrong machine(s) within the budget get past the %d drops a card shows" % [level.id, late, level.card_shows])
		return -1
	if needed < level.card_shows and level.card_shows > int(level.raw.get("card_shows_min", 0)):
		_fail("%s: cards show %d drops but %d decode it (rerun make cards)" % [level.id, level.card_shows, needed])
	return needed


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------

## Cheapest machine up to max_cost: {"cost": int (-1 if none), "program": String, "combos": int, "states": int}.
func solve(level, inventions: Dictionary, max_cost: int, without := "") -> Dictionary:
	# Distinct combinations of card colors, and what each must weave.
	var combo_of := {}
	var combos := []
	var want := []
	for i in level.size():
		var key := []
		for c in level.cards:
			key.append(c[i])
		var k := str(key)
		if not combo_of.has(k):
			combo_of[k] = combos.size()
			combos.append(key)
			want.append(level.target[i])
		elif want[combo_of[k]] != level.target[i]:
			_fail("%s: same card colors must weave two different stitches" % level.id)
			return {"cost": -1, "program": "impossible", "combos": combos.size(), "states": 0}
	chunks = int(ceil(combos.size() / float(LANES)))
	full_mask = _const_vec(combos.size(), Paint.BLACK)
	low_mask = _const_vec(combos.size(), Paint.RED | Paint.YELLOW)
	high_mask = _const_vec(combos.size(), Paint.BLUE)
	red_vec = _const_vec(combos.size(), Paint.RED)
	combo_count = combos.size()
	has_split = "split" in level.pieces
	target_key = str(_pack(want))
	ops = level_ops(level, inventions).filter(func(o): return o.get("id", "") != without or without == "")
	for o in ops:
		if o["op"] == "paint":
			o["v"] = _const_vec(combos.size(), o["paint"])
	var signals := []
	var names := ["A", "B", "C", "D"]
	for k in level.cards.size():
		var col := []
		for combo in combos:
			col.append(combo[k])
		var v := _pack(col)
		signals.append({"v": v, "key": str(v), "desc": names[k]})
	card_signals = signals.duplicate()
	nodes_seen = 0
	for limit in max_cost + 1:
		visited = {}
		found = ""
		if (_dfs(signals, 0, limit) if "split" in level.pieces else _dfs_tree(signals, 0, limit)):
			return {"cost": limit, "program": found, "combos": combos.size(), "states": nodes_seen}
	return {"cost": -1, "program": "", "combos": combos.size(), "states": nodes_seen}


func _dfs(signals: Array, used: int, limit: int) -> bool:
	nodes_seen += 1
	for s in signals:
		if s["key"] == target_key:
			found = s["desc"]
			return true
	if used >= limit:
		return false
	var keys := []
	for s in signals:
		keys.append(s["key"])
	keys.sort()
	var state := "|".join(keys)
	if visited.get(state, 1 << 30) <= used:
		return false
	visited[state] = used
	var have := {}
	for s in signals:
		have[s["key"]] = true
	for gate in _gates(signals, limit - used):
		if have.has(gate["key"]):
			continue
		signals.append(gate)
		var ok := _dfs(signals, used + gate["cost"], limit)
		signals.pop_back()
		if ok:
			return true
	return false


## The same search for levels without Split: every result feeds at most one
## piece, so a gate uses up its inputs (a second pot is a new piece).
func _dfs_tree(signals: Array, used: int, limit: int) -> bool:
	nodes_seen += 1
	for s in signals:
		if s["key"] == target_key:
			found = s["desc"]
			return true
	if used >= limit:
		return false
	var keys := []
	for s in signals:
		keys.append(s["key"])
	keys.sort()
	var state := "|".join(keys)
	if visited.get(state, 1 << 30) <= used:
		return false
	visited[state] = used
	for gate in _gates(signals, limit - used):
		var next := []
		for k in signals.size():
			if not k in gate["ins"]:
				next.append(signals[k])
		next.append(gate)
		if _dfs_tree(next, used + gate["cost"], limit):
			return true
	return false


## The pieces a level offers, as search operations: its basic pieces, the
## earned pots it opens (a paint at the pot's price) and its inventions (at
## their price, by what they compute).
static func level_ops(level, inventions: Dictionary) -> Array:
	var out := []
	for kind in level.pieces:
		if kind in ["red_pot", "mix", "filter", "invert", "shift"]:
			out.append({"op": kind, "cost": 1, "name": kind.capitalize()})
	for pot_id in level.pots:
		if inventions.has(pot_id):
			var inv: Dictionary = inventions[pot_id]
			out.append({"op": "paint", "paint": Invention.paint_of(inv), "cost": int(inv["cost"]), "name": inv["name"].replace(" pot", ""), "id": pot_id})
	for inv_id in level.inventions:
		if inventions.has(inv_id):
			var inv: Dictionary = inventions[inv_id]
			if inv["check"] in BINARY or inv["check"] in ["invert", "shift"]:
				out.append({"op": inv["check"], "cost": int(inv["cost"]), "name": inv["name"].replace(" ", ""), "id": inv_id})
	return out


## Every piece that can be added to the current signals within the budget.
func _gates(signals: Array, budget: int) -> Array:
	var out := []
	var n := signals.size()
	for o in ops:
		if o["cost"] > budget:
			continue
		match o["op"]:
			"red_pot":
				out.append({"v": red_vec, "key": str(red_vec), "desc": "Red", "cost": o["cost"], "ins": []})
			"paint":
				var pv: PackedInt64Array = o["v"]
				out.append({"v": pv, "key": str(pv), "desc": o["name"] + "Pot", "cost": o["cost"], "ins": []})
			"invert", "shift":
				for k in n:
					var s: Dictionary = signals[k]
					var v := _unary(o["op"], s["v"])
					out.append({"v": v, "key": str(v), "desc": "%s(%s)" % [o["name"], s["desc"]], "cost": o["cost"], "ins": [k]})
			_:  # two inputs; every one of them is the same either way round
				for i in n:
					for j in range(i if has_split else i + 1, n):  # one paint into both takes a Split
						var v := _binary(o["op"], signals[i]["v"], signals[j]["v"])
						out.append({"v": v, "key": str(v), "desc": "%s(%s, %s)" % [o["name"], signals[i]["desc"], signals[j]["desc"]], "cost": o["cost"], "ins": [i, j] if i != j else [i]})
	return out


func _unary(op: String, a: PackedInt64Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	for c in chunks:
		if op == "invert":
			out[c] = a[c] ^ full_mask[c]
		else:
			out[c] = ((a[c] & low_mask[c]) << 1) | ((a[c] & high_mask[c]) >> 2)
	return out


func _binary(op: String, a: PackedInt64Array, b: PackedInt64Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	for c in chunks:
		match op:
			"mix":
				out[c] = a[c] | b[c]
			"filter":
				out[c] = a[c] & b[c]
			"contrast":
				out[c] = a[c] ^ b[c]
			"third_paint":
				out[c] = (a[c] | b[c]) ^ full_mask[c]
			"missing_from_either":
				out[c] = (a[c] & b[c]) ^ full_mask[c]
			"same_paint":
				out[c] = (a[c] ^ b[c]) ^ full_mask[c]
	return out


func _pack(colors: Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	out.fill(0)
	for i in colors.size():
		out[i / LANES] = out[i / LANES] | (int(colors[i]) << (3 * (i % LANES)))
	return out


func _const_vec(count: int, color: int) -> PackedInt64Array:
	var col := []
	for i in count:
		col.append(color)
	return _pack(col)
