## Finds the cheapest machine for every campaign level.
##
## Run from the project folder:
##   godot_console --headless --path . --script res://tools/level_solver.gd
## Writes docs/level-report.md and exits with code 1 if a level is broken:
## its reference solution fails, it can't be solved by any machine, or a
## machine cheaper than its three-star count exists.
##
## Why a search is enough: with one-drop tubes every piece takes one drop per
## input and gives one per output, and loops can never start (a loop waits on
## itself). So every working machine weaves stitch i from the i-th color of
## each card: it is a function of the cards. The search tries every function
## that the level's pieces can build, cheapest first, and compares it with
## the target on the card colors the level actually uses. Splits are free, so
## any result can feed any number of pieces.
extends SceneTree

const Paint = preload("res://core/paint.gd")
const Level = preload("res://core/level.gd")
const Simulator = preload("res://core/simulator.gd")
const Invention = preload("res://core/invention.gd")

const LANES := 20  # colors packed per int (3 flags each)

var problems := 0
var chunks := 0
var full_mask := PackedInt64Array()
var low_mask := PackedInt64Array()
var high_mask := PackedInt64Array()
var red_vec := PackedInt64Array()
var target_key := ""
var ops: Array = []
var visited := {}
var found := ""
var nodes_seen := 0


func _init() -> void:
	var t0 := Time.get_ticks_msec()
	var levels := Level.load_all()
	var inventions := _reference_inventions(levels)
	var lines := PackedStringArray()
	lines.append("# Chromaton level report")
	lines.append("")
	lines.append("Generated by `tools/level_solver.gd` on %s. Rerun after changing levels or pieces:" % Time.get_date_string_from_system())
	lines.append("")
	lines.append("```")
	lines.append("godot_console --headless --path . --script res://tools/level_solver.gd")
	lines.append("```")
	lines.append("")
	lines.append("**Cheapest** is the fewest pieces any machine needs to weave the level (splits free where the level offers them, otherwise each result feeds one piece; the Filter invention at its reference price of %d). It is found by trying every machine the level's pieces can build, cheapest first. Three stars need the cheapest count; two stars need the budget." % int(inventions.get("filter", {}).get("cost", 0)))
	lines.append("")
	lines.append("| Level | Stitches | Cards | Card combos | Reference | Ticks | Cheapest | Cheapest machine | ★★ budget | ★★★ best |")
	lines.append("|---|---|---|---|---|---|---|---|---|---|")
	for level in levels:
		if level.error != "":
			_fail(level.error)
			continue
		var m = level.reference_machine()
		var sim = Simulator.new(m, level.cards, level.target, inventions)
		sim.run()
		var ref_cost: int = m.cost(inventions)
		if sim.status != Simulator.Status.SOLVED:
			_fail("%s: reference solution does not solve the level (status %d, stitch %d)" % [level.id, sim.status, sim.wrong_index])
		if ref_cost != level.best:
			_fail("%s: reference uses %d pieces but best is %d" % [level.id, ref_cost, level.best])
		if level.budget < level.best:
			_fail("%s: budget %d is under best %d" % [level.id, level.budget, level.best])
		var res := solve(level, inventions, level.best)
		var cheapest: String = str(res["cost"]) if res["cost"] >= 0 else "> %d" % level.best
		if res["cost"] >= 0 and res["cost"] < level.best:
			_fail("%s: a %d-piece machine exists (%s), cheaper than best %d" % [level.id, res["cost"], res["program"], level.best])
		if res["cost"] < 0:
			_fail("%s: no machine of up to %d pieces found" % [level.id, level.best])
		lines.append("| %s | %d | %d | %d | %d | %d | %s | `%s` | %d | %d |" % [
			level.name, level.size(), level.cards.size(), res["combos"], ref_cost, sim.tick,
			cheapest, res["program"], level.budget, level.best])
		print("%s: cheapest %s  %s  (%d states)" % [level.id, cheapest, res["program"], res["states"]])
	lines.append("")
	lines.append("---")
	lines.append("")
	lines.append("Checks: %s. Run time %.1f s." % ["all passed" if problems == 0 else "%d problem(s)" % problems, (Time.get_ticks_msec() - t0) / 1000.0])
	var f := FileAccess.open("res://docs/level-report.md", FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	quit(1 if problems > 0 else 0)


func _fail(msg: String) -> void:
	problems += 1
	printerr("PROBLEM: " + msg)


## The inventions the reference solutions use: each invention level's own reference.
static func _reference_inventions(levels: Array) -> Dictionary:
	var inventions := {}
	for level in levels:
		if not level.invention.is_empty():
			var m = level.reference_machine()
			inventions[level.invention["id"]] = Invention.package(level, m, inventions)
	return inventions


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------

## Cheapest machine up to max_cost: {"cost": int (-1 if none), "program": String, "combos": int, "states": int}.
func solve(level, inventions: Dictionary, max_cost: int) -> Dictionary:
	# Distinct combinations of card colors, and what each must weave.
	var combo_of := {}
	var combos := []
	var want := []
	for i in level.size():
		var key := []
		for c in level.cards:
			key.append(c[i])
		var k := str(key)
		if not combo_of.has(k):
			combo_of[k] = combos.size()
			combos.append(key)
			want.append(level.target[i])
		elif want[combo_of[k]] != level.target[i]:
			_fail("%s: same card colors must weave two different stitches" % level.id)
			return {"cost": -1, "program": "impossible", "combos": combos.size(), "states": 0}
	chunks = int(ceil(combos.size() / float(LANES)))
	full_mask = _const_vec(combos.size(), Paint.BLACK)
	low_mask = _const_vec(combos.size(), Paint.RED | Paint.YELLOW)
	high_mask = _const_vec(combos.size(), Paint.BLUE)
	red_vec = _const_vec(combos.size(), Paint.RED)
	target_key = str(_pack(want))
	ops = []
	for kind in level.pieces:
		if kind in ["red_pot", "mix", "invert", "shift"]:
			ops.append({"op": kind, "cost": 1})
	for inv_id in level.inventions:
		if inv_id == "filter" and inventions.has("filter"):
			ops.append({"op": "filter", "cost": int(inventions["filter"]["cost"])})
	var signals := []
	var names := ["A", "B", "C", "D"]
	for k in level.cards.size():
		var col := []
		for combo in combos:
			col.append(combo[k])
		var v := _pack(col)
		signals.append({"v": v, "key": str(v), "desc": names[k]})
	nodes_seen = 0
	for limit in max_cost + 1:
		visited = {}
		found = ""
		if (_dfs(signals, 0, limit) if "split" in level.pieces else _dfs_tree(signals, 0, limit)):
			return {"cost": limit, "program": found, "combos": combos.size(), "states": nodes_seen}
	return {"cost": -1, "program": "", "combos": combos.size(), "states": nodes_seen}


func _dfs(signals: Array, used: int, limit: int) -> bool:
	nodes_seen += 1
	for s in signals:
		if s["key"] == target_key:
			found = s["desc"]
			return true
	if used >= limit:
		return false
	var keys := []
	for s in signals:
		keys.append(s["key"])
	keys.sort()
	var state := "|".join(keys)
	if visited.get(state, 1 << 30) <= used:
		return false
	visited[state] = used
	var have := {}
	for s in signals:
		have[s["key"]] = true
	for gate in _gates(signals, limit - used):
		if have.has(gate["key"]):
			continue
		signals.append(gate)
		var ok := _dfs(signals, used + gate["cost"], limit)
		signals.pop_back()
		if ok:
			return true
	return false


## The same search for levels without Split: every result feeds at most one
## piece, so a gate uses up its inputs (a second pot is a new piece).
func _dfs_tree(signals: Array, used: int, limit: int) -> bool:
	nodes_seen += 1
	for s in signals:
		if s["key"] == target_key:
			found = s["desc"]
			return true
	if used >= limit:
		return false
	var keys := []
	for s in signals:
		keys.append(s["key"])
	keys.sort()
	var state := "|".join(keys)
	if visited.get(state, 1 << 30) <= used:
		return false
	visited[state] = used
	for gate in _gates(signals, limit - used):
		var next := []
		for k in signals.size():
			if not k in gate["ins"]:
				next.append(signals[k])
		next.append(gate)
		if _dfs_tree(next, used + gate["cost"], limit):
			return true
	return false


## Every piece that can be added to the current signals within the budget.
func _gates(signals: Array, budget: int) -> Array:
	var out := []
	var n := signals.size()
	for o in ops:
		if o["cost"] > budget:
			continue
		match o["op"]:
			"red_pot":
				out.append({"v": red_vec, "key": str(red_vec), "desc": "Red", "cost": o["cost"], "ins": []})
			"invert", "shift":
				for k in n:
					var s: Dictionary = signals[k]
					var v := _unary(o["op"], s["v"])
					out.append({"v": v, "key": str(v), "desc": "%s(%s)" % [o["op"].capitalize(), s["desc"]], "cost": o["cost"], "ins": [k]})
			"mix", "filter":
				for i in n:
					for j in range(i + 1, n):
						var v := _binary(o["op"], signals[i]["v"], signals[j]["v"])
						out.append({"v": v, "key": str(v), "desc": "%s(%s, %s)" % [o["op"].capitalize(), signals[i]["desc"], signals[j]["desc"]], "cost": o["cost"], "ins": [i, j]})
	return out


func _unary(op: String, a: PackedInt64Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	for c in chunks:
		if op == "invert":
			out[c] = a[c] ^ full_mask[c]
		else:
			out[c] = ((a[c] & low_mask[c]) << 1) | ((a[c] & high_mask[c]) >> 2)
	return out


func _binary(op: String, a: PackedInt64Array, b: PackedInt64Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	for c in chunks:
		out[c] = (a[c] | b[c]) if op == "mix" else (a[c] & b[c])
	return out


func _pack(colors: Array) -> PackedInt64Array:
	var out := PackedInt64Array()
	out.resize(chunks)
	out.fill(0)
	for i in colors.size():
		out[i / LANES] = out[i / LANES] | (int(colors[i]) << (3 * (i % LANES)))
	return out


func _const_vec(count: int, color: int) -> PackedInt64Array:
	var col := []
	for i in count:
		col.append(color)
	return _pack(col)
